### ISSUE TITLE
主打一个辣鸡，跑不通啊作者

### ISSUE THREAD

**Issue by kitty-nami** [limengran98/SCAE#1]

**Comment by limengran98** [comment]
您好，我在本地尝试，代码能正常运行。如果您遇到了问题，请提供详细的错误信息或运行环境，这样我可以帮助您排查和解决问题。

另外我上传了所有环境的requirements文件。

Github是一个开放且合作的社区，礼貌和尊重是非常重要的。如果您有任何疑问或建议，欢迎以建设性的方式表达，我会尽全力帮助您解决问题并改进项目。

感谢理解！
